openapi: '3.0.1'
info:
  title: API - User
  version: 0.0.1

paths:
  /api/users/{id}:
    get:
      tags:
        - Users
      operationId: user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: "int64"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                  name:
                    type: "string"
